"""baseline schema

Revision ID: f429a0a33015
Revises: 
Create Date: 2026-09-15 15:46:46.153669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f429a0a33015'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_superadmin', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admins_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_admins_id'), ['id'], unique=False)

    op.create_table('akg_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ageGroup', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('energy', sa.String(), nullable=True),
    sa.Column('protein', sa.String(), nullable=True),
    sa.Column('fat', sa.String(), nullable=True),
    sa.Column('carbs', sa.String(), nullable=True),
    sa.Column('vitA', sa.String(), nullable=True),
    sa.Column('vitC', sa.String(), nullable=True),
    sa.Column('iron', sa.String(), nullable=True),
    sa.Column('calcium', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('akg_targets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_akg_targets_id'), ['id'], unique=False)

    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('read_time_min', sa.Integer(), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_articles_id'), ['id'], unique=False)

    op.create_table('foods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('energy', sa.Float(), nullable=True),
    sa.Column('protein', sa.Float(), nullable=True),
    sa.Column('carbs', sa.Float(), nullable=True),
    sa.Column('fat', sa.Float(), nullable=True),
    sa.Column('safe', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('foods', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_foods_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_foods_name'), ['name'], unique=False)

    op.create_table('growth_standards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('metric', sa.String(), nullable=True),
    sa.Column('age', sa.String(), nullable=True),
    sa.Column('p3', sa.String(), nullable=True),
    sa.Column('p15', sa.String(), nullable=True),
    sa.Column('p50', sa.String(), nullable=True),
    sa.Column('p85', sa.String(), nullable=True),
    sa.Column('p97', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('growth_standards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_growth_standards_id'), ['id'], unique=False)

    op.create_table('milestones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('min_months', sa.Integer(), nullable=False),
    sa.Column('max_months', sa.Integer(), nullable=False),
    sa.Column('age_label', sa.String(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('expected', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('milestones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_milestones_id'), ['id'], unique=False)

    op.create_table('parents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('parents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parents_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_parents_id'), ['id'], unique=False)

    op.create_table('children',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('children', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_children_id'), ['id'], unique=False)

    op.create_table('health_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('vaccine_code', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('child_id', 'vaccine_code', name='uq_child_vaccine_dose')
    )
    with op.batch_alter_table('health_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_health_events_child_id'), ['child_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_health_events_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_health_events_id'), ['id'], unique=False)

    op.create_table('meal_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=True),
    sa.Column('food_name', sa.String(), nullable=False),
    sa.Column('meal_type', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('servings', sa.Float(), nullable=False),
    sa.Column('energy', sa.Float(), nullable=False),
    sa.Column('protein', sa.Float(), nullable=False),
    sa.Column('carbs', sa.Float(), nullable=False),
    sa.Column('fat', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meal_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meal_logs_child_id'), ['child_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meal_logs_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_meal_logs_id'), ['id'], unique=False)

    op.create_table('measurement_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=True),
    sa.Column('date_logged', sa.DateTime(), nullable=True),
    sa.Column('age_in_days', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('wfa_zscore', sa.Float(), nullable=True),
    sa.Column('lhfa_zscore', sa.Float(), nullable=True),
    sa.Column('wfh_zscore', sa.Float(), nullable=True),
    sa.Column('bfa_zscore', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('measurement_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_measurement_logs_id'), ['id'], unique=False)

    op.create_table('milestone_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('milestone_id', sa.Integer(), nullable=False),
    sa.Column('achieved', sa.Boolean(), nullable=False),
    sa.Column('answered_on', sa.Date(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('child_id', 'milestone_id', name='uq_child_milestone')
    )
    with op.batch_alter_table('milestone_answers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_milestone_answers_child_id'), ['child_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_milestone_answers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_milestone_answers_milestone_id'), ['milestone_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('milestone_answers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_milestone_answers_milestone_id'))
        batch_op.drop_index(batch_op.f('ix_milestone_answers_id'))
        batch_op.drop_index(batch_op.f('ix_milestone_answers_child_id'))

    op.drop_table('milestone_answers')
    with op.batch_alter_table('measurement_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_measurement_logs_id'))

    op.drop_table('measurement_logs')
    with op.batch_alter_table('meal_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meal_logs_id'))
        batch_op.drop_index(batch_op.f('ix_meal_logs_date'))
        batch_op.drop_index(batch_op.f('ix_meal_logs_child_id'))

    op.drop_table('meal_logs')
    with op.batch_alter_table('health_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_health_events_id'))
        batch_op.drop_index(batch_op.f('ix_health_events_date'))
        batch_op.drop_index(batch_op.f('ix_health_events_child_id'))

    op.drop_table('health_events')
    with op.batch_alter_table('children', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_children_id'))

    op.drop_table('children')
    with op.batch_alter_table('parents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parents_id'))
        batch_op.drop_index(batch_op.f('ix_parents_email'))

    op.drop_table('parents')
    with op.batch_alter_table('milestones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_milestones_id'))

    op.drop_table('milestones')
    with op.batch_alter_table('growth_standards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_growth_standards_id'))

    op.drop_table('growth_standards')
    with op.batch_alter_table('foods', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_foods_name'))
        batch_op.drop_index(batch_op.f('ix_foods_id'))

    op.drop_table('foods')
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_articles_id'))

    op.drop_table('articles')
    with op.batch_alter_table('akg_targets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_akg_targets_id'))

    op.drop_table('akg_targets')
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admins_id'))
        batch_op.drop_index(batch_op.f('ix_admins_email'))

    op.drop_table('admins')
    # ### end Alembic commands ###
